[package]
name = "tokio-lite"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
futures = "0.3.31"
mio = "1.1.1"
slab = "0.4.11"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7", features = ["full"] }
