[package]
name = "Tokio-Lite"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
slab = "0.4.11"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7", features = ["full"] }
